#define CHAR_HEIGHT 15
#define Y_OFFSET 3
#define ROW_HEIGHT 15

#define IDLE GRect(144/2,168/2,0,0)
				//(x, y, w, h)
#define TWENTY GRect(0,(0 * ROW_HEIGHT) + Y_OFFSET,72,CHAR_HEIGHT)
#define THIR GRect(71,(0 * ROW_HEIGHT) + Y_OFFSET,38,CHAR_HEIGHT)
#define FIVE GRect(108,(0 * ROW_HEIGHT) + Y_OFFSET,36,CHAR_HEIGHT)
	
#define SEVEN GRect(1,(1 * ROW_HEIGHT) + Y_OFFSET,56,CHAR_HEIGHT)
#define FOUR GRect(56,(1 * ROW_HEIGHT) + Y_OFFSET,47,CHAR_HEIGHT)
#define NINE GRect(102,(1 * ROW_HEIGHT) + Y_OFFSET,41,CHAR_HEIGHT)
	
#define TWO GRect(0,(2 * ROW_HEIGHT) + Y_OFFSET,40,CHAR_HEIGHT)
#define ONE GRect(26,(2 * ROW_HEIGHT) + Y_OFFSET,37,CHAR_HEIGHT)
#define EIGH GRect(52,(2 * ROW_HEIGHT) + Y_OFFSET,39,CHAR_HEIGHT)
#define EIGHT GRect(52,(2 * ROW_HEIGHT) + Y_OFFSET,49,CHAR_HEIGHT)
#define THREE GRect(90,(2 * ROW_HEIGHT) + Y_OFFSET,54,CHAR_HEIGHT)
	
#define SIX GRect(4,(3 * ROW_HEIGHT) + Y_OFFSET,27,CHAR_HEIGHT)
#define TWELVE GRect(30,(3 * ROW_HEIGHT) + Y_OFFSET,68,CHAR_HEIGHT)
#define TEEN GRect(97,(3 * ROW_HEIGHT) + Y_OFFSET,44,CHAR_HEIGHT)
	
#define ELEVEN GRect(0,(4 * ROW_HEIGHT) + Y_OFFSET,65,CHAR_HEIGHT)
#define QUARTER GRect(64,(4 * ROW_HEIGHT) + Y_OFFSET,79,CHAR_HEIGHT)
	
#define TEN GRect(1,(5 * ROW_HEIGHT) + Y_OFFSET,34,CHAR_HEIGHT)
#define HALF GRect(34,(5 * ROW_HEIGHT) + Y_OFFSET,44,CHAR_HEIGHT)
#define TO GRect(77,(5 * ROW_HEIGHT) + Y_OFFSET,24,CHAR_HEIGHT)
#define PAST GRect(100,(5 * ROW_HEIGHT) + Y_OFFSET,44,CHAR_HEIGHT)
	
#define H_EIGHT GRect(3,(6 * ROW_HEIGHT) + Y_OFFSET,49,CHAR_HEIGHT)
#define H_THREE GRect(41,(6 * ROW_HEIGHT) + Y_OFFSET,54,CHAR_HEIGHT)
#define H_FOUR GRect(94,(6 * ROW_HEIGHT) + Y_OFFSET,47,CHAR_HEIGHT)
	
#define H_TWO GRect(4,(7 * ROW_HEIGHT) + Y_OFFSET,40,CHAR_HEIGHT)
#define H_TEN GRect(43,(7 * ROW_HEIGHT) + Y_OFFSET,34,CHAR_HEIGHT)
#define H_ONE GRect(76,(7 * ROW_HEIGHT) + Y_OFFSET,37,CHAR_HEIGHT)
#define H_SIX GRect(112,(7 * ROW_HEIGHT) + Y_OFFSET,27,CHAR_HEIGHT)
	
#define H_SEVEN GRect(3,(8 * ROW_HEIGHT) + Y_OFFSET,56,CHAR_HEIGHT)
#define MIDNIGHT GRect(58,(8 * ROW_HEIGHT) + Y_OFFSET,84,CHAR_HEIGHT)
	
#define H_NINE GRect(2,(9 * ROW_HEIGHT) + Y_OFFSET,41,CHAR_HEIGHT)
#define H_ELEVEN GRect(42,(9 * ROW_HEIGHT) + Y_OFFSET,65,CHAR_HEIGHT)
#define H_FIVE GRect(106,(9 * ROW_HEIGHT) + Y_OFFSET,36,CHAR_HEIGHT)
	
#define MIDDAY GRect(1,(10 * ROW_HEIGHT) + Y_OFFSET,68,CHAR_HEIGHT)
#define OCLOCK GRect(68,(10 * ROW_HEIGHT) + Y_OFFSET,75,CHAR_HEIGHT)